### ISSUE TITLE
DESTDIR not respected during zig build

### ISSUE THREAD

**Issue by alerque** [ghostty-org/ghostty#3152]
Using the `DESTDIR` as advertised in PACKAGING.md does *not* work, it still tries to write things directly to the prefix directory. Only using `--prefix "$DESTDIR/usr"` seems to work for me.

**Comment by BratishkaErik** [comment]
This is because `b.install_prefix` is used in https://github.com/ghostty-org/ghostty/blob/a8e5eef11cc67f87f445626f9ca2993373774bf8/build.zig#L483-L499, which does not account for DESTDIR unlike `b.install_path`. One solution can be to use `b.addInstallDirectory` here instead of calling `cp`, like it's done in Gentoo patch:
```diff
-                const copy_step = RunStep.create(b, "copy terminfo db");
-                copy_step.addArgs(&.{ "cp", "-R" });
-                copy_step.addFileArg(path);
-                copy_step.addArg(b.fmt("{s}/share", .{b.install_prefix}));
-                b.getInstallStep().dependOn(&copy_step.step);
+                const install_dir_step = b.addInstallDirectory(.{
+                    .source_dir = path,
+                    .install_dir = .prefix,
+                    .install_subdir = "share/terminfo",
+                });
+                b.getInstallStep().dependOn(&install_dir_step.step);
```

Otherwise, as a fast fix just replace `install_prefix` with `install_path`.
