### ISSUE TITLE
[BUG 🐞] open configuration Arch Linux

### ISSUE THREAD

**Issue by DiegoDev2** [ghostty-org/ghostty#3334]
When choosing the option to open settings it does nothing
![Image](https://github.com/user-attachments/assets/4ac8562d-4a2b-40cf-bc05-980318a17ac5)

**Comment by pandalec** [comment]
Works for me. Do you have an xdg default application for text files?

**Comment by DiegoDev2** [comment]
Oh no. I thought it came by default in the minimal installation in arch, which one do you recommend? @pandalec

**Comment by pandalec** [comment]
Use your preferred text editor, e.g. GNOME Text Editor if you are on GNOME, or Kate if you use KDE and so on

**Comment by carnager** [comment]
using a terminal based editor only works, when a 2nd instance of ghostty is spawned from within the first instance.

**Comment by alesitom** [comment]
Still reproducible on Ubuntu (GNOME) — March 2026

"Open Config File" does nothing. No error shown in the UI.

- OS: Ubuntu (GNOME desktop)
- gnome-text-editor is installed and set as default for text/plain via `xdg-mime`
- Running xdg-open `~/.config/ghostty/config` from a terminal works fine
- Running gnome-text-editor `~/.config/ghostty/config` directly also works
- The issue seems to be in how Ghostty invokes the system opener internally

Workaround: Open the config manually from the terminal.

**Comment by rhodes-b** [comment]
> Still reproducible on Ubuntu (GNOME) — March 2026
> 
> "Open Config File" does nothing. No error shown in the UI.
> 
>     * OS: Ubuntu (GNOME desktop)
> 
>     * gnome-text-editor is installed and set as default for text/plain via `xdg-mime`
> 
>     * Running xdg-open `~/.config/ghostty/config` from a terminal works fine
> 
>     * Running gnome-text-editor `~/.config/ghostty/config` directly also works
> 
>     * The issue seems to be in how Ghostty invokes the system opener internally
> 
> 
> Workaround: Open the config manually from the terminal.

this post is over a year old open a new discussion under issue triage
