### ISSUE TITLE
Rendering issue with zsh-autosuggestions through SSH

### ISSUE THREAD

**Issue by punoko** [ghostty-org/ghostty#3338]
This is what is being rendered when using [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions) through an SSH session after typing "date" followed by backspace x3. (iTerm2 on the right for comparison)

<img width="1710" alt="Image" src="https://github.com/user-attachments/assets/e2393420-76f8-4488-8193-3d354db5cbfe" />

No issue observed outside of SSH. Happy to provide more info as needed.

**Comment by punoko** [comment]
Probably a duplicate of https://github.com/ghostty-org/ghostty/issues/3335

**Comment by weareDMNTRs** [comment]
Yes, it’s exactly the same behavior.

**Comment by anund** [comment]
See https://github.com/ghostty-org/ghostty/issues/3335#issuecomment-2563509690

**Comment by codeinred** [comment]
## Why this issue occurs

**Link to Terminfo documentation, which was very helpful:** https://ghostty.org/docs/help/terminfo

This issue occurs because the remote machine doesn't understand how to handle `$TERM=xterm-ghostty`. 

## How to solve this issue

Option 1: [Copy Ghostty's terminfo to a remote machine](https://ghostty.org/docs/help/terminfo)

```bash
infocmp -x | ssh YOUR-SERVER -- tic -x -
```

Option 2: [Configure SSH to report a known terminfo entry](https://ghostty.org/docs/help/terminfo)

```
# .ssh/config
Host example.com
  SetEnv TERM=xterm-256color
```

## Will this issue occur in the future?

[The documentation says:](https://ghostty.org/docs/help/terminfo)

> Ghostty's terminfo entry has been merged into ncurses. As distros update their ncurses packages, Ghostty's terminfo entry will be available by default system-wide. This will take time to propagate.
