### ISSUE TITLE
$XDG_CONFIG_HOME not used on macOS even if set

### ISSUE THREAD

**Issue by zachvalenta** [ghostty-org/ghostty#3456]
I have `$XDG_CONFIG_HOME` set:
```sh
echo $XDG_CONFIG_HOME # /Users/zvalenta/.config
```

[Based on the docs](https://ghostty.org/docs/config): `macOS also supports the XDG location`

I expected the config file to be there: `$XDG_CONFIG_HOME/ghostty/config (all platforms)`

But instead it's using the macOS default (when `$XDG_CONFIG_HOME` is not set):
```sh
test -f ~/Library/Application\ Support/com.mitchellh.ghostty/config && echo "exists" || echo "does not exist"  # exists
```

Not a big problem, I just:
* removed `~/Library/Application\ Support/com.mitchellh.ghostty/config`
* manually created the path and file `/Users/zvalenta/.config/ghostty/config`

But figured worth raising as a point of friction/confusion.

Great project and glad to be using it!

**Comment by mitchellh** [comment]
#3203 related.

The file has to exist for it to be used, not just the directory.

**Comment by smst329** [comment]
Please reopen. I am experiencing this.

```bash
% ls $XDG_CONFIG_HOME/ghostty
config
cat $XDG_CONFIG_HOME/ghostty/config
background = 282c34
foreground = 282c00
```

Those config settings are what they are not because they are ideal but just to test if changing values changes the terminal.  Changing the settings and reloading config does nothing. Using ghostty menu item to open settings files, does not open the file at the XDG path but the default path. Which is a blank file because I deleted the original as an attempted fix.

**Comment by 00-kat** [comment]
A lot has changed since then, open a new discussion → https://github.com/ghostty-org/ghostty/discussions/new?category=issue-triage.
